### ISSUE TITLE
SID filter always starts off as disabled and filter curve settings also ignored.

### ISSUE THREAD

**Issue by KynikossDragonn** [libsidplayfp/sidplayfp#1]
I've recently just updated to the 2.1.0 release and thought my INI wasn't being read, but it appears the UseFilter, FilterBias, FilterCurve6581, and FilterCurve8580 settings aren't being applied... and strangely enough UseFilter is being marked as disabled.

Every other option in the INI seems to work including forcing the SID model, but all the filter options aren't read and the filter is disabled, even in verbose it says "SID Filter: No".

**Comment by drfiemost** [comment]
Good catch, I've messed the configuration in the latest release, fixed with cbc8a727253ca9688b08d7a089dc7e7e3bf00ca7
