### ISSUE TITLE
WAV file extension is appended

### ISSUE THREAD

**Issue by maxim-zhao** [libsidplayfp/sidplayfp#10]
The docs say:

> \<name\> IS NOT checked for or appended with a legal wav file extension.

This used to be true, but the [current code does this](https://github.com/libsidplayfp/sidplayfp/blob/master/src/player.cpp#L329):
```
title.append(WavFile::extension());
```

Can you make it do one or the other? Ideally, it might add the extension only if the passed filename doesn't already have it.

**Comment by drfiemost** [comment]
Fixed with the above commit.

**Comment by maxim-zhao** [comment]
Thanks!
