### ISSUE TITLE
stilview: handle character conversion

### ISSUE THREAD

**Issue by drfiemost** [libsidplayfp/sidplayfp#16]
i.e.
```
$ stilview  -e=/MUSICIANS/V/Vaca_Ramiro/Turrican.sid -t=3
NAME: The Deep
AUTHOR: Chris H�lsbeck
COMMENT: Re-edit of /MUSICIANS/H/Huelsbeck_Chris/Compilation_III.sid, Tune #4.
```

**Comment by mywave82** [comment]
Which character encoding is your terminal btw?

**Comment by drfiemost** [comment]
It's UTF8

**Comment by mywave82** [comment]
Please double check that the fault is not in SID file before digging yourself deep in, they should be stored in latin1 which is one way compatible with UTF-8. Atleast to my knowledge

**Comment by drfiemost** [comment]
No, they're compatible only for the ASCII part, see for example https://en.wikipedia.org/wiki/%C3%9C#Computing_codes
The same is already done in the player for the song info using iconv.

**Comment by mywave82** [comment]
You're right, I forgot the encoding. Latin1 converts directly into 8bit unicodes as is, but needs the utf-8 encoding to be applied.
