### ISSUE TITLE
add default run flags on sidplayfp.ini.

### ISSUE THREAD

**Issue by red-M95** [libsidplayfp/sidplayfp#22]
title says it all, so for example, if i want sidplayfp to have `--delay=4096 -rr -v2` every time i run it, instead of running `sidplayfp --delay=4096 -rr -v2` all the time, i can just specify it on sidplayfp.ini, something like this:
`[SIDPlayfp]`
`...`
`Default Flags = --delay=4096 -rr -v2`

**Comment by drfiemost** [comment]
Well, I've never seen something like that, but sure it's possible to add the single options to the config file (like Delay, Resampling and Verbose).

**Comment by red-M95** [comment]
yeah, i got that idea from another program, don't remember which, but it worked similarly.

**Comment by red-M95** [comment]
i saw, i'm using it right now, and i think you could remove `FastSampling` to cover it with `Sampling`, so you have:
`Sampling = <INTERPOLATE|RESAMPLE[,fast]>` (so not specifying `fast` makes it not use fast sampling).

**Comment by drfiemost** [comment]
Actually it's a resid specific option so I'd like to keep it separate, even better renaming it to ResidFastSampling or moving it to a different section.

**Comment by drfiemost** [comment]
Ok, I might consider this for a future release. Moving to a new ticket and closing this one.
