### ISSUE TITLE
console output not sync'ed to the sound when running with ALSA

### ISSUE THREAD

**Issue by ruby-R53** [libsidplayfp/sidplayfp#31]
when compiling sidplayfp with ALSA support only, the verbose output (`-v2`'s notes, control registers, and more) is updated really fast, not following what's currently being played. the time count seems to be only a tiny bit faster than normal though

i pulled the latest version from here, but i remember this also happening when installing from the gentoo repositories without the `pulseaudio` USE flag a while ago

**Comment by drfiemost** [comment]
No problem here with ALSA.
Can you please try again with the latest change? (https://github.com/libsidplayfp/sidplayfp/commit/2bf29448052c1fe067f8a81681038b8a4d518782)

**Comment by ruby-R53** [comment]
that's weird, now the output runs really fast until it hits the 12-second mark, then it continues at the normal speed, while the song plays at normal speed the whole time so it doesn't get sync'ed here neither

**Comment by drfiemost** [comment]
I've been able to reproduce this by setting the frequency to 8000, it skips first couple of seconds then plays normally.
Guess this is the same as #20

**Comment by ruby-R53** [comment]
hmm, as i lower the sample rate the skipping goes further

i had it set to 192 kHz, now i set to 96 and it skips the first 27 seconds, then when setting to 48 it skips the first 54 seconds, and so on

**Comment by mywave82** [comment]
Is this the same issue as #20 ?

**Comment by ruby-R53** [comment]
yeah, seems like it

**Comment by drfiemost** [comment]
Ok, let's continue the discussion over at #20
