### ISSUE TITLE
Some SID's play wrong.

### ISSUE THREAD

**Issue by Spike1978** [libsidplayfp/sidplayfp#34]
I encountered a SID that sounds absolutely horrible with v2.6.2
I downgraded to v2.5.0 and everything sounds normal again.
The SID in question is: https://hvsc.csdb.dk/MUSICIANS/M/Mythus/Devotion.sid
I have no idea if the bug is in the library or the player but something is definitely wrong.

**Comment by drfiemost** [comment]
It has to do with the combined waveforms, the model has been changed in 2.6.
If you try the latest release 2.7, setting `CombinedWaveforms = STRONG` in sidplayfp.ini, it sounds good again.
