### ISSUE TITLE
Note detection off by a semitone when forcing PAL/NTSC signal via command line

### ISSUE THREAD

**Issue by ruby-R53** [libsidplayfp/sidplayfp#37]
When using either `-vnf` or `-vpf`, sidplayfp still uses the frequency table specified by the tune to display the notes, and that makes the note display off by one semitone.

I tried fixing it by editing `args.cpp` and repointing `m_freqTable` to `freqTablePal`/`freqTableNtsc` when `-vpf`/`-vnf` is used but I couldn't.

I'm using sidplayfp's latest release.

**Comment by drfiemost** [comment]
Should be fixed in master, can you please check?

**Comment by ruby-R53** [comment]
it's working!
