### ISSUE TITLE
Some (sub)tunes don't end, they just restart instead

### ISSUE THREAD

**Issue by ruby-R53** [libsidplayfp/sidplayfp#39]
For some reason, the player restarts some tunes instead of actually ending them using the Songlength database.

Some examples are Tim Follin's `Ghouls_n_Ghosts.sid` (subtune 1) and Devilock's `Intro_Zak_2_for_711.sid` (single tune), and one other that I couldn't remember the name :P

The player reaches the specified duration and just restarts the tune all over again, and then I have to manually go to the next one.

It also happens if I set the same duration on the command line. If I set the duration to something else however, it plays normally. So I'm assuming there's some code at the end of these tunes that somehow triggers sidplayfp into thinking it has to start from the beginning, or I might be saying some nonsense.

EDIT: oh yeah and this has been happening to me since the first time I used sidplayfp.

**Comment by drfiemost** [comment]
Which version of HVSC are you using? Here with #81 `/MUSICIANS/F/Follin_Tim/Ghouls_n_Ghosts.sid` works fine while for `/MUSICIANS/D/Devilock/Intro_Zak_2_for_711.sid` the songlength fail to load for some reason which I have to investigate.
Also did you use the `--enable-testsuite` for the library? It may introduce undesired behaviour for normal listening.

**Comment by drfiemost** [comment]
> for `/MUSICIANS/D/Devilock/Intro_Zak_2_for_711.sid` the songlength fail to load for some reason which I have to investigate.

File was corrupted, downloaded a fresh one and it stops correctly at 1:33

**Comment by ruby-R53** [comment]
> Which version of HVSC are you using?

i'm using the latest version, #81

> Also did you use the --enable-testsuite for the library? It may introduce undesired behaviour for normal listening.

i didn't, it's configured with the default flags

> File was corrupted, downloaded a fresh one and it stops correctly at 1:33

well i redownloaded the HVSC to see if i didn't have a faulty `Songlengths.md5` or PSID files, no difference whatsoever

**Comment by drfiemost** [comment]
Hard to tell... anything in the config file or the command line? ROMs are loaded? If so which versions?

**Comment by ruby-R53** [comment]
i have Kernal revision 3, BASIC V2, and the character generator

**Comment by drfiemost** [comment]
Same here, but I'm unable to reproduce. If you can find any hints, like compiler flags, configurations or whatever, let me know.
Oh, and which OS are you using?

**Comment by ruby-R53** [comment]
i'm using Gentoo, but i'm running both sidplayfp and libsidplayfp from their latest commit on github

**Comment by ruby-R53** [comment]
UPDATE: i installed libsidplayfp and sidplayfp on my laptop to test

it did work normally, BUT when i loaded the ROMs there it had the same issue

and then i went to my PC and also removed the ROMs there to try, and it played normally just like in my laptop

should i now try to remove the ROMs one by one to find out if there's one specific ROM causing that issue?

**Comment by ruby-R53** [comment]
exactly the same setup that i have

**Comment by ruby-R53** [comment]
> I suspect it's the kernal.

well i tried running it without the Kernal ROM only and it did work normally, so yeah

**Comment by ruby-R53** [comment]
UPDATE: found another tune that has the same issue, it's `Great_Giana_Sisters.sid` at subtune 5

now i wanna know what those tunes have in common that messes sidplayfp up a bit...

**Comment by ruby-R53** [comment]
UPDATE:

> and one other that I couldn't remember the name :P

i just remembered it!! it was `MUSICIANS/L/Laxity/Mikuk.sid`

**Comment by drfiemost** [comment]
Are you using pulseaudio? That might be the difference

**Comment by ruby-R53** [comment]
ahh yeah i am

gonna try it with ALSA now

**Comment by ruby-R53** [comment]
yeah it does work when running with ALSA but for some weird reason the register dumps don't get in sync with the audio, they run in a low frame rate as if i was recording to a file instead

but that should be discussed in a separate issue

**Comment by drfiemost** [comment]
A bit late for the release but should be fixed now, it was an uncatched error.

**Comment by ruby-R53** [comment]
well it did work for `Great_Giana_Sisters.sid`, but for `Intro_Zak_2_for_711` it displayed `Bad buffer size` when finished

i'm assuming it actually displayed that same error for the former tune as well but it switched to the next subtune so fast i couldn't catch it

**Comment by drfiemost** [comment]
Oh right, that was only half of the issue...
More to come

**Comment by ruby-R53** [comment]
welp, one other thing i just discovered is that playing those tunes with PulseAudio makes sidplayfp crash instead of ignoring the error and moving to the next tune, which's the case with out123 (what i had first)

**Comment by ruby-R53** [comment]
(https://github.com/libsidplayfp/libsidplayfp/issues/159)
> Should help with https://github.com/libsidplayfp/sidplayfp/issues/39 and https://github.com/libsidplayfp/sidplayfp/issues/4

hey, it actually did!! for the latter it also seemed to have fixed it but not when recording to a .wav (a few hundred miliseconds beyond the songlength gets recorded, not sure if it matters much)

plus, it seemed to have produced some audio glitches on Jeroen Tel & LMan's `Skypeople.sid`, but that should be discussed in a different issue

**Comment by drfiemost** [comment]
> hey, it actually did!! for the latter it also seemed to have fixed it but not when recording to a .wav (a few hundred milliseconds beyond the songlength gets recorded, not sure if it matters much)

Good, so can we close this? And please add your notes to the relevant issue so they don't get lost.

> plus, it seemed to have produced some audio glitches on Jeroen Tel & LMan's `Skypeople.sid`, but that should be discussed in a different issue

If you mean the clicking noises I can reproduce it with 2.9.0 too so it doesn't look like a regression.

**Comment by ruby-R53** [comment]
> Good, so can we close this? And please add your notes to the relevant issue so they don't get lost.

yup! got it

> If you mean the clicking noises I can reproduce it with 2.9.0 too so it doesn't look like a regression.

quite the opposite rather, it skips a few samples at times but only during playback, when recorded it sounds completely fine

i actually noticed that pattern with other songs made in GoatTracker 2, so here's that

**Comment by drfiemost** [comment]
So there are still buffer problems :/
Just file another issue at [libsidplayfp](https://github.com/libsidplayfp/libsidplayfp)
