### ISSUE TITLE
Does not play \MUSICIANS\B\Bjerregaard_Johannes\Nightdawn.sid correctly

### ISSUE THREAD

**Issue by acrouzet** [libsidplayfp/sidplayfp#42]
When trying to play track 1, it simply closes after a split second. It does plays the other tracks, but they sound completely messed up.

**Comment by ruby-R53** [comment]
i can reproduce that by removing the KERNAL ROM file, so maybe it'll work for you if you add a KERNAL ROM file (if it hasn't been added already)

**Comment by acrouzet** [comment]
I see no KERNAL ROM file in my windows binary folder.

**Comment by ruby-R53** [comment]
it [already is](https://github.com/libsidplayfp/sidplayfp/blob/master/doc/en/sidplayfp.pod#NOTES), unless you mean something clearer than that?

**Comment by acrouzet** [comment]
I see, for some reason my eyes skipped over that. Thanks!

**Comment by ruby-R53** [comment]
lol you're welcome!
