### ISSUE TITLE
Set FilterRange in command line?

### ISSUE THREAD

**Issue by acrouzet** [libsidplayfp/sidplayfp#47]

**Comment by ruby-R53** [comment]
i was thinking of suggesting that as well

**Comment by drfiemost** [comment]
> EDIT: or suggesting the filter parameters setup to be similar to the way VICE's player does, which's by sliding across milivolt values and not selecting some 0 to 1 double values, the former is much more intuitive (at least to me) but i'm not sure if it's doable here

For now I'll keep the 0..1 range to maintain compatibility. Also the filter range is measured in A/V^2, not really user friendly.

**Comment by ruby-R53** [comment]
yeah that makes sense
