### ISSUE TITLE
The sample muting #define does not get set properly

### ISSUE THREAD

**Issue by aquamarine-axo** [libsidplayfp/sidplayfp#49]
According to [this commit](<https://github.com/libsidplayfp/sidplayfp/commit/98c2545e9bdea23b8479aa0fd07f6d26270061d6>), sample muting should now be functional and added to the in-program documentation shown when running the program with no arguments. When building from git master using the typical `autoreconf -i; ./configure; make; sudo make install`, however, the line showing the options for `-g` do not appear in the in-program documentation, and running `-g(1|2|3)` makes the program complain about an invalid option, and pressing q, w, or e in the player do nothing. 

Despite being 2.10.0a and compiled from git master as of tonight, the flag to enable these features appears to not be set properly. 

(Perhaps tangentially, while I have no real C++ experience I tried to modify the code to comment out all of the `#define`s relating to sample muting, and while the `-gN` option was accepted, and the documentation appeared, it did not mute anything. But I very well could have done something wrong in the process.)

**Comment by ruby-R53** [comment]
> Despite being 2.10.0a

both the lib and the player itself? the sample muting feature was added like a week ago on both, so they should be in the same latest version for that to work

**Comment by drfiemost** [comment]
guess this can be closed
