### ISSUE TITLE
Support for muting samples

### ISSUE THREAD

**Issue by minttukone** [libsidplayfp/sidplayfp#5]
I use sidplayfp for splitting SID files into individual channels, and it works fine for songs that don't use digisamples, but when I have to split songs that have digisamples, although sidplayfp plays the digisamples properly, you need to patch the SID file to do so. Maybe there is an option to mute samples, but I haven't found one yet.
This is roughly why it would be great to see a feature in sidplayfp to mute samples.

**Comment by drfiemost** [comment]
Samples are not a feature but a side effect, also there are different techniques for playing digis. I don't see an obvious way to mute them, maybe some sort of digiboost could help for volume register based samples on 6581, but overall I don't see a reliable solution to this request.

**Comment by drfiemost** [comment]
I guess you mean only the low nibble of $D418? Interesting trick, will give it a spin and maybe put it in the TODO list for the lib.

**Comment by acrouzet** [comment]
> A flag that disables all writes to the $D418 volume register would disable the traditional sample playback, and solve this problem. Bonus points for isolating the samples by interpreting _only_ the volume register noises,

Sample isolation can currently be achieved by simply muting all the channels. The problem is that since the samples affect the volume, cancellation of the samples via inversion will still leave very audible (and visible) artifacts.
