### ISSUE TITLE
Set combined wave strength in command line as well?

### ISSUE THREAD

**Issue by acrouzet** [libsidplayfp/sidplayfp#51]

**Comment by acrouzet** [comment]
Wouldn't you just add something like this to args.cpp? I tried this and it works on residfp for me.

`#ifdef FEAT_CW_STRENGTH
            else if (std::strcmp (&argv[i][1], "cww") == 0)
            {
                m_combinedWaveformsStrength  = SidConfig::WEAK;
            }
            else if (std::strcmp (&argv[i][1], "cwa") == 0)
            {
                m_combinedWaveformsStrength  = SidConfig::AVERAGE;
            }
            else if (std::strcmp (&argv[i][1], "cws") == 0)
            {
                m_combinedWaveformsStrength  = SidConfig::STRONG;
            }	
#endif`

**Comment by drfiemost** [comment]
Yeah, it might do. Feel free to open a PR, or I'll get to this later on.
If you do please update the help message and doc too.
