### ISSUE TITLE
Make audio buffer size configurable

### ISSUE THREAD

**Issue by drfiemost** [libsidplayfp/sidplayfp#52]
As the title says, add an ini setting to specify the buffer length in milliseconds.

**Comment by ruby-R53** [comment]
funny how i was about to open an issue mentioning exactly that lol

**Comment by ruby-R53** [comment]
oh yeah, one other thing i forgot to mention is that increasing the audio buffer size in sidplayfp makes the register dump display skip some frames to match with that size (?), at least when using PulseAudio

can this be fixed or is it just some insignificant detail?

**Comment by drfiemost** [comment]
Maybe we can use a separate thread to update the display...

**Comment by ruby-R53** [comment]
yeah, would also help with display flickering as a bonus maybe

**Comment by drfiemost** [comment]
Available on master, please test

**Comment by ruby-R53** [comment]
yeah the display is getting updated every 250 ms apparently, on both out123 and PulseAudio builds

it seems to have helped a bit with libsidplayfp#161 tho', i can still notice some inconsistencies with `Gordian_Tomb.sid` but they're more subtle now

**Comment by ruby-R53** [comment]
UPDATE: i also noticed that when selecting/replaying a tune, you hear some of it sorta leaking out after that brief moment of silence between the tune selection

**Comment by ruby-R53** [comment]
> when selecting/replaying a tune, you hear some of it sorta leaking out after that brief moment of silence between the tune selection

coming to think of it, maybe this was already happening before this buffer thing was changed? however, the buffer size was so small it was almost unnoticeable

**Comment by drfiemost** [comment]
yeah, I've noticed the same, will look into it.

**Comment by drfiemost** [comment]
Is it better now after last change?

**Comment by ruby-R53** [comment]
yup, i don't hear that leakage anymore but that silent part between each tune is a bit longer, not a big deal tho'
