### ISSUE TITLE
Song titles aren't loaded correctly if Windows system locale is Japanese

### ISSUE THREAD

**Issue by webbedspace** [libsidplayfp/sidplayfp#7]
The song "Knyt(nävs)kalas" (at C64Music\MUSICIANS\Q\Qdor\Knyt_naevs_kalas.sid) becomes "Knyt(n舸s)kalas", for instance.

**Comment by drfiemost** [comment]
Which codepage are you using?

**Comment by drfiemost** [comment]
Added a few more codepages in latest release, @webbedspace please let me know if it's fixed.

**Comment by drfiemost** [comment]
Then it's a foo_sid problem, the library doesn't perform any character conversion.
